EventBundle_event_annotation:
    resource: "@EventBundle/Controller"
    prefix:   /
    type:     annotation

event_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /

event_homepage:
    path:     /hello/{name}/{count}
    defaults: { _controller: EventBundle:Default:index }
