user_routes:
    resource: "@UserBundle/Controller"
    type: annotation

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
